### PR TITLE
Allow for more customization.

### PR DESCRIPTION
**Pull request by pisaiah**
allow user to control if logging messages is enabled (Not 100% done)

### CODE REVIEW

**Comment by LexManos** [comment]
First option can be done via log4j's config system.
And second doesn't really make sense except to just cut out the word Minecraft

**Comment by pisaiah** [comment]
Example for second, if a server mod was using launchwrapper it could be configured to say "Loading server"

**Comment by LexManos** [comment]
I understand the functionality I just personally don't think it's needed. I'll let grum decide. But my input is 1st isn't needed and second isn't needed if anything changing to it "Launching wrapped application: %s" would be the better solution not a argument.

**Comment by grum** [comment]
Logger control should be through the loggers configuration.
I'm not sure on the need to change or suppress the message it is logging right now. Is there a good reason to do so that justifies a commit, change in behavior and subsequent release of something neither vanilla nor forge is likely going to use?

**Comment by stephan-gh** [comment]
The same thing can already be achieved using a custom log4j2 configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
    ...
    <Loggers>
        <!-- Suppress all INFO messages by LaunchWrapper -->
        <Logger name="LaunchWrapper" level="warn"/>
    </Loggers>
</Configuration>
```

Making the launch message configurable isn't really useful either because you can just log a different message if you hide the original message with the configuration above.

**Pull request closed without merging**
