### PR TITLE
Correct typos. Closes #6

### LINKED ISSUE #6: Small Typo
in / src / main / java / net / minecraft / launchwrapper / injector / VanillaTweakInjector.java
on line 80 there seems to be a typo: "turning of" instead of "turning off"

### PR DESCRIPTION
**Pull request by jamierocks**
Everytime I see this repo, I see #6, so I decided to fix it :P

### CODE REVIEW

**Comment by liach** [comment]
:(

**Comment by jamierocks** [comment]
?

**Comment by liach** [comment]
#7 #8 LexManos might **** you.

**Comment by jamierocks** [comment]
Eh, I didn't see those. Perhaps this pr will break the previous pattern.

**Comment by grum** [comment]
Bop! I might remember it next time I release this =D

**Comment by jamierocks** [comment]
That would be cool :D

**Pull request closed without merging**
